// The icon dictionary (docs/UI-GUIDE.md §4): one concept = one icon, everywhere.
// Screens import icons from here, never straight from lucide-react, so changing a
// concept's icon is a one-line edit.
import {
  AlarmClock,
  ArrowLeftRight,
  Armchair,
  Ban,
  Banknote,
  BadgePercent,
  BookOpenCheck,
  Building2,
  CalendarDays,
  CircleDollarSign,
  Clock,
  CreditCard,
  Download,
  FileCheck,
  FileText,
  Hourglass,
  IndianRupee,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LibraryBig,
  LogOut,
  MoveRight,
  Pencil,
  Phone,
  Plus,
  Printer,
  ReceiptText,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Trash2,
  Undo2,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
} from "lucide-react";

export const ICONS = Object.freeze({
  library: LibraryBig,
  dashboard: LayoutDashboard,
  seatMap: Armchair,
  members: Users,
  member: User,
  addMember: UserPlus,
  waitlist: Hourglass,
  layout: LayoutGrid,
  slots: Clock,
  staff: UserCog,
  settings: Settings,
  libraries: Building2,
  platformSettings: SlidersHorizontal,
  password: KeyRound,
  signOut: LogOut,
  payment: IndianRupee,
  receipt: ReceiptText,
  dues: AlarmClock,
  expenses: Wallet,
  ledger: BookOpenCheck,
  deposit: ShieldCheck,
  refund: Undo2,
  discount: BadgePercent,
  charge: FileText,
  export: Download,
  print: Printer,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  void: Ban,
  move: MoveRight,
  swap: ArrowLeftRight,
  endBooking: LogOut,
  phone: Phone,
  date: CalendarDays,
  search: Search,
});

/** Payment-mode icons (cash, UPI, card, bank, cheque, other, online). */
export const PAYMENT_MODE_ICONS = Object.freeze({
  cash: Banknote,
  upi: Smartphone,
  card: CreditCard,
  bank: Landmark,
  cheque: FileCheck,
  online: Smartphone,
  other: CircleDollarSign,
});
