// The icon dictionary (docs/UI-GUIDE.md §4): one concept = one icon, everywhere —
// in the admin app and the student app alike. Screens import icons from here
// ("@app/shared/icons"), never straight from lucide-react, so changing a concept's
// icon is a one-line edit.
import {
  AlarmClock,
  Armchair,
  ArrowLeftRight,
  BadgePercent,
  Ban,
  Banknote,
  Bell,
  BellOff,
  BookOpenCheck,
  Building2,
  CalendarCheck,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  CircleUserRound,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  FileCheck,
  FileText,
  Flame,
  Hourglass,
  House,
  IdCard,
  IndianRupee,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LibraryBig,
  LogIn,
  LogOut,
  MapPin,
  MoveRight,
  Pencil,
  Phone,
  Plus,
  Printer,
  QrCode,
  ReceiptText,
  ScanLine,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  UserX,
  Wallet,
  X,
} from "lucide-react";

export const ICONS = Object.freeze({
  library: LibraryBig,
  dashboard: LayoutDashboard,
  seatMap: Armchair,
  members: Users,
  member: User,
  addMember: UserPlus,
  waitlist: Hourglass,
  layout: LayoutGrid,
  slots: Clock,
  staff: UserCog,
  settings: Settings,
  libraries: Building2,
  platformSettings: SlidersHorizontal,
  password: KeyRound,
  signOut: LogOut,
  payment: IndianRupee,
  receipt: ReceiptText,
  dues: AlarmClock,
  expenses: Wallet,
  ledger: BookOpenCheck,
  attendance: CalendarCheck,
  checkin: QrCode,
  checkedIn: LogIn,
  deposit: ShieldCheck,
  refund: Undo2,
  discount: BadgePercent,
  charge: FileText,
  export: Download,
  print: Printer,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  void: Ban,
  move: MoveRight,
  swap: ArrowLeftRight,
  endBooking: LogOut,
  phone: Phone,
  date: CalendarDays,
  search: Search,
  markPresent: UserCheck,
  markAbsent: UserX,
  close: X,
  previous: ChevronLeft,
  next: ChevronRight,
  // Student app (milestone 7)
  home: House,
  profile: CircleUserRound,
  scan: ScanLine,
  streak: Flame,
  idCard: IdCard,
  notifications: Bell,
  notificationsOff: BellOff,
  insights: TrendingUp,
  mockTest: ClipboardList,
  installApp: Smartphone,
  location: MapPin,
});

/** Payment-mode icons (cash, UPI, card, bank, cheque, other, online). */
export const PAYMENT_MODE_ICONS = Object.freeze({
  cash: Banknote,
  upi: Smartphone,
  card: CreditCard,
  bank: Landmark,
  cheque: FileCheck,
  online: Smartphone,
  other: CircleDollarSign,
});
